# -*- coding: utf-8 -*-
"""DaviAula1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UcXiJ7Eh85U5e6O3OdrPbzTFjhoqGkH4

# Exercício 1
"""

print('Olá, eu sou uma IA criada pelo aluno!')

"""# Exercício 2"""

numero1 = int(input('Digite um número: '))
numero2 = int(input('Digite outro número: '))

print(f'A soma de {numero1} + {numero2} = {numero1 + numero2}')
print(f'O produto de {numero1} x {numero2} = {numero1 * numero2}')

if numero1 > numero2:
  print(f'O maior número é: {numero1}')
else:
  print(f'O maior número é: {numero2}')

"""# Exercício 3"""

numero = int(input('Digite um número: '))

if numero % 2 == 0:
  print('Eu, IA, detectei um número par')
else:
  print('Eu, IA, detectei um número ímpar')

"""# Exercício 4"""

sentimento = input('Como você está se sentindo hoje? ').lower()

if sentimento == 'feliz':
  print('Que bom! Feliz por você.')
elif sentimento == 'triste':
  print('Que pena! faça algo que te alegre.')
elif sentimento == 'com sono':
  print('Talvez você precise dormir mais cedo')
else:
  print('Esse setimento ainda não possuo em minha base de dados')

"""# Exercício 5"""

nota1 = float(input('Digite a nota da 1ª prova: '))
nota2 = float(input('Digite a nota da 2ª prova: '))
nota3 = float(input('Digite a nota da 3ª prova: '))
media = (nota1 + nota2 + nota3) / 3

print(f'Sua média é: {media}')

if media >= 7:
  print('Você está APROVADO!')
elif media < 7:
  print('Voce está de RECUPERAÇÃO!')
else:
  print('Você está de REPROVADO!')

"""# Exercício 6"""

def contar_palavras(frase):
    frase_limpa = ' '.join(frase.split())

    contador_palavras = 0

    if frase_limpa:
        contador_palavras = 1

    for caractere in frase_limpa:
        if caractere == ' ':
            contador_palavras += 1

    return contador_palavras

frase_usuario = input('Digite uma frase: ')

total_palavras = contar_palavras(frase_usuario)

print(f'A frase {frase_usuario} possui {total_palavras} palavras')

"""# Exercício 7"""

nome = input('Digite seu nome: ')
hora = int(input('Digite a hora em inteiro, sem minutos: '))

if hora >= 18 and hora <= 24:
  print(f'Boa noite {nome}')
elif hora >= 12 and hora < 18:
  print(f'Boa tarde {nome}')
elif hora >= 6 and hora < 12:
  print(f'Bom dia {nome}')
else:
  print('Horário não existente')

"""# Exercício 8"""

temperaturas = []
soma = 0.0

for i in range(5):
  valor = float(input(f'Digite a {i +1}ª temperatura: '))

  temperaturas.append(valor)
print(temperaturas)

for temp in temperaturas:
  soma = soma + temp

if len(temperaturas) > 0:
  media = soma / 5
  print(f'A média das temperaturas é: {media}')
else:
  print('A lista de temperaturas está vazia')

maior_temp = temperaturas[0]
menor_temp = temperaturas[0]
contador = 0

for temp in temperaturas:
  if temp > maior_temp:
    maior_temp = temp
  if temp < menor_temp:
    menor_temp = temp
  if temp > 30:
    contador = contador + 1

print(f'A maior temperatura é: {maior_temp}')
print(f'A menor temperatura é: {menor_temp}')
print(f'{contador} temperaturas estão acima de 30ºC')

"""# Exercício 9"""

alunos = [
    {
        'Nome': 'Felipe',
        'Nota': 8
    },
    {
        'Nome': 'Matheus',
        'Nota': 9
    },
    {
        'Nome': 'Luana',
        'Nota': 7
    },
    {
        'Nome': 'Gabriel',
        'Nota': 8
    },
    {
        'Nome': 'Bianca',
        'Nota': 6
    }
]

alunos_aprovados = [
    aluno for aluno in alunos if aluno['Nota'] > 7
]

for aluno in alunos_aprovados:
  print(f'{aluno['Nome']}: Nota {aluno['Nota']}')

"""# Exercício 10"""

import random

def ia_aleatorio(pergunta):
    respostas = ['Sim', 'Não', 'Talvez']

    resposta = random.choice(respostas)

    return resposta

pergunta = input('Digite uma pergunta: ')
resposta = ia_aleatorio(pergunta)

print(f'Sua pergunta: {pergunta}')
print(f'Resposta IA: {resposta}')

"""# Exercício 11"""

total_letras = 0
total_vogais = 0
total_consoantes = 0
vogais = 'aeiou'

palavra = input('Digite uma palavra: ').lower()

for caractere in palavra:
  if 'a' <= caractere <= 'z':
    total_letras = total_letras + 1

    if caractere in vogais:
      total_vogais = total_vogais + 1

    else:
      total_consoantes = total_consoantes + 1

print(f'Sua Palavra: {palavra} \nTotal de letras: {total_letras} \nTotal de vogais: {total_vogais} \nTotal de consoantes: {total_consoantes}')

"""# Exercício 12"""

def verificar_frase_proibida():
    PALAVRAS_PROIBIDAS = [
        "ódio",
        "spam",
        "golpe",
        "fraude",
        "matar"
    ]

    frase = input("Digite sua frase: ").lower()
    encontrada_proibida = None

    for palavra_proibida in PALAVRAS_PROIBIDAS:
        if palavra_proibida in frase:
            encontrada_proibida = palavra_proibida
            break

    if encontrada_proibida:
        print(f'A frase contém a palavra proibida: {encontrada_proibida}')
        print('Por favor, reformule sua mensagem.')
    else:
        print('Frase aceita.')
        print(f'Mensagem enviada: {frase}')

verificar_frase_proibida()

"""# Exercício 13"""

import matplotlib.pyplot as plt

def plotar_notas_alunos():
    alunos = [
        {'Nome': 'Felipe', 'Nota': 8},
        {'Nome': 'Matheus', 'Nota': 9},
        {'Nome': 'Luana', 'Nota': 7},
        {'Nome': 'Gabriel', 'Nota': 8},
        {'Nome': 'Bianca', 'Nota': 6}
    ]

    nomes = [aluno['Nome'] for aluno in alunos]
    notas = [aluno['Nota'] for aluno in alunos]

    plt.style.use('ggplot')

    plt.figure(figsize=(10, 6))
    plt.bar(nomes, notas, color='skyblue')

    plt.title('Desempenho dos Alunos em Python')
    plt.xlabel('Nome do Aluno')
    plt.ylabel('Nota Final')

    media = sum(notas) / len(notas)
    plt.axhline(media, color='red', linestyle='--', linewidth=1, label=f'Média: {media:.2f}')

    for i, nota in enumerate(notas):
        plt.text(i, nota + 0.1, str(nota), ha='center', va='bottom')

    plt.legend()

    plt.xticks(rotation=45, ha='right')

    plt.tight_layout()
    plt.show()

plotar_notas_alunos()

"""# Exercício 14"""

import random

def gerar_frase_aleatoria(quantidade=1):
    substantivos = ["gato", "cachorro", "programador", "nuvem", "computador", "lua", "robô"]
    adjetivos = ["rápido", "verde", "silencioso", "gigante", "feliz", "curioso", "misterioso"]
    verbos = ["corre", "escreve", "dorme", "flutua", "desenha", "canta", "analisa"]
    adverbios = ["lentamente", "alegremente", "rapidamente", "sempre", "cuidadosamente", "cedo"]
    artigos = ["O", "Um", "A", "Uma"]

    frases_geradas = []

    for _ in range(quantidade):
        artigo_escolhido = random.choice(artigos)
        adjetivo_escolhido = random.choice(adjetivos)
        substantivo_escolhido = random.choice(substantivos)
        verbo_escolhido = random.choice(verbos)
        adverbio_escolhido = random.choice(adverbios)

        frase = f'{artigo_escolhido} {adjetivo_escolhido} {substantivo_escolhido} {verbo_escolhido} {adverbio_escolhido}'

        frases_geradas.append(frase)

    for i, frase in enumerate(frases_geradas):
        print(f'Frase {i+1}: {frase}')

gerar_frase_aleatoria(quantidade=3)

"""# Exercício 15"""

def calcular_e_classificar_media(nota1, nota2, nota3):
    media = (nota1 + nota2 + nota3) / 3

    media_formatada = f'{media:.2f}'

    status = ''

    if media >= 7.0:
        status = 'APROVADO'
    elif media >= 5.0:
        status = 'EM RECUPERAÇÃO'
    else:
        status = 'REPROVADO'

    print('-' * 35)
    print(f'Notas recebidas: {nota1}, {nota2}, {nota3}')
    print(f'Média calculada: {media_formatada}')
    print(f'Status do Aluno: {status}')
    print('-' * 35)

    return status

calcular_e_classificar_media(8.5, 7.0, 9.5)
calcular_e_classificar_media(6.0, 4.5, 5.5)
calcular_e_classificar_media(3.0, 4.0, 4.5)

"""# Exercício 16"""

def classificar_email_spam(texto):
    palavras_gatilho = [
        'grátis', 'dinheiro fácil', 'clique aqui',
        'urgente', 'parabéns', 'ganhe', 'bônus',
        'oferta especial', 'por apenas', 'você é um vencedor',
        'sem riscos', 'liberdade financeira', 'eliminar a dívida',
        'remédio milagroso', 'compre agora', 'tempo limitado'
    ]

    texto_limpo = texto.lower()

    pontuacao_spam = 0
    palavras_encontradas = []

    for palavra in palavras_gatilho:
        if palavra in texto_limpo:
            pontuacao_spam += 1
            palavras_encontradas.append(palavra)

    LIMITE_SPAM = 3

    status = ''

    if pontuacao_spam >= LIMITE_SPAM:
        status = 'CLASSIFICADO COMO SPAM'
    else:
        status = 'CLASSIFICADO COMO NÃO-SPAM'

    print('=' * 50)
    print(f'TEXTO AVALIADO: \'{texto}\'')
    print('-' * 50)
    print(f'Palavras Gatilho Encontradas ({pontuacao_spam} pontos):')

    if palavras_encontradas:
        print(f"-> {', '.join(palavras_encontradas)}")
    else:
        print('-> Nenhuma palavra gatilho encontrada.')

    print('-' * 50)
    print(f'CLASSIFICAÇÃO FINAL: {status}')
    print('=' * 50)

    return status

classificar_email_spam('Parabéns! Você ganhou na loteria. Clique aqui para receber seu dinheiro fácil e grátis!')
classificar_email_spam('Nosso novo ebook grátis sobre Python está disponível para download.')
classificar_email_spam('Olá, segue a ata da reunião. Por favor, revise e me retorne.')

"""# Exercício 17"""

def organizar_numeros():
    resultados = {
        'pares': [],
        'impares': [],
        'positivos': [],
        'negativos': [],
        'zeros': []
    }

    QUANTIDADE_NUMEROS = 10

    for i in range(QUANTIDADE_NUMEROS):
        while True:
            try:
                numero = int(input(f'Digite o {i+1}º número: '))
                break
            except ValueError:
                print('Entrada inválida. Por favor, digite um número inteiro.')

        if numero % 2 == 0:
            resultados['pares'].append(numero)
        else:
            resultados['impares'].append(numero)

        if numero > 0:
            resultados['positivos'].append(numero)
        elif numero < 0:
            resultados['negativos'].append(numero)
        else:
            resultados['zeros'].append(numero)

    print('\n' + '=' * 40)
    print('ORGANIZAÇÃO DOS NÚMEROS NO DICIONÁRIO:')
    print('=' * 40)

    print(f'Pares: {resultados["pares"]}')
    print(f'Ímpares: {resultados["impares"]}')
    print(f'Positivos: {resultados["positivos"]}')
    print(f'Negativos: {resultados["negativos"]}')
    print(f'Zeros: {resultados["zeros"]}')
    print('=' * 40)

organizar_numeros()

"""# Exercício 18"""

def chatbot_simples():
    print('Olá! Eu sou o BotPython. Digite \'sair\' a qualquer momento para encerrar.')

    while True:
        entrada = input('Você: ').lower().strip()

        if entrada == 'sair':
            print('BotPython: Tchau! Foi bom conversar com você.')
            break

        elif 'olá' in entrada or 'oi' in entrada:
            print('BotPython: Olá! Como posso te ajudar hoje?')

        elif 'tudo bem' in entrada or 'como você está' in entrada:
            print('BotPython: Eu sou um programa de computador, mas estou ótimo, obrigado por perguntar!')

        elif 'o que é python' in entrada:
            print('BotPython: Python é uma linguagem de programação poderosa e fácil de aprender.')

        elif 'obrigado' in entrada or 'valeu' in entrada:
            print('BotPython: De nada! Estou aqui para ajudar.')

        else:
            print('BotPython: Hummm, não tenho uma resposta específica para isso. Poderia tentar outra pergunta?')

chatbot_simples()

"""# Exercício 19"""

from collections import Counter
import string

def analisar_texto():
    texto = input('Digite o texto a ser analisado: ')

    texto_minusculo = texto.lower()

    letras_apenas = ''.join(c for c in texto_minusculo if c.isalpha())

    texto_sem_pontuacao = texto_minusculo.translate(str.maketrans('', '', string.punctuation))

    total_caracteres = len(texto)

    palavras = list(filter(None, texto_sem_pontuacao.split()))
    total_palavras = len(palavras)

    palavra_mais_longa = ''
    if palavras:
        palavra_mais_longa = max(palavras, key=len)

    contagem_letras = Counter(letras_apenas)
    letra_mais_frequente = ''
    frequencia = 0

    if contagem_letras:
        letra_mais_frequente, frequencia = contagem_letras.most_common(1)[0]

    print('\n' + '=' * 40)
    print('RESULTADOS DA ANÁLISE DE TEXTO')
    print('=' * 40)
    print(f'Total de Caracteres (com espaços): {total_caracteres}')
    print(f'Total de Palavras: {total_palavras}')
    print('-' * 40)
    print(f'Palavra Mais Longa: {palavra_mais_longa} ({len(palavra_mais_longa)} letras)')
    print(f'Letra Mais Frequente: {letra_mais_frequente} ({frequencia} ocorrências)')
    print('=' * 40)

analisar_texto()