# -*- coding: utf-8 -*-
"""aspirador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BtfPISPZ-wd4s6nYgXOMzKzmJiEKGItv
"""

import os
class Aspirador:
  def __init__(self, pos, ambiente):
    self.posicao = pos
    self.ambiente = ambiente
    self.celulas_limpas =[]

  def lerSensor(self):
    for k in range(3):
      raio = 1 + k
      print("Raio: "+str(raio))

      start_i = max(0, self.posicao[0] - raio)
      end_i = min(len(self.ambiente), self.posicao[0] + raio + 1)

      start_j = max(0, self.posicao[1] - raio)
      end_j = min(len(self.ambiente[0]), self.posicao[1] + raio + 1)

      for i in range(start_i, end_i):
        for j in range(start_j, end_j):

          if i == self.posicao[0] and j == self.posicao[1]:
            continue

          print(f"Varrendo célula [{i}][{j}]...")

          if self.ambiente[i][j] == 1:
            self.limpar(i,j)

  def limpar(self, i, j):
    print(f"LIMPOU a célula [{i}][{j}]")
    self.posicao = [i,j]
    self.ambiente[i][j] = 0
    self.celulas_limpas.append([i, j])

ambiente = [
    [0,0,0],
    [0,0,1],
    [1,0,1]
    ]

pos = [1,1]
meurobo = Aspirador(pos, ambiente)
meurobo.lerSensor()

print(f'Foram limpas as células {meurobo.celulas_limpas} pelo aspirador')